---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: nginx-v2
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx2
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: nginx2.default.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: nginx-router
  namespace: default
spec:
  listeners:
    - portMapping:
        port: 80
        protocol: http
  routes:
    - name: nginx-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: nginx-v1
              weight: 90
            - virtualNodeRef:
                name: nginx-v2
              weight: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      serviceAccountName: default-envoy-proxies
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: default
  labels:
    app: nginx2
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: nginx2
---
