---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    mesh: default-mesh
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: default-mesh
spec:
  namespaceSelector:
    matchLabels:
      mesh: default-mesh
---
